name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  golint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          
  horusec:
    name: Identify Vulnerabilities
    runs-on: ubuntu-latest
    
    needs: ['golint']
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true"

  build:
    needs: horusec

    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Clone Repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0
        
      - name: Setup Go (latest)
        uses: actions/setup-go@v3
      
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      
      - name: Exec Script
        run: psql -h postgres -d postgres -U postgres -a -f  resources/test.sql
        env:
          PGPASSWORD: postgres
      
      - name: Run unity test
        run: |
          mkdir -p bin
          go test -short -coverprofile=bin/cov.out ./...

      - name: Run benchmark
        run: |
          go test -bench 'Benchmark' ./... | tee bin/bench.txt
          
      - name: Archive code coverage and bench results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: bin
