name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  golint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          
  Vulnerability:
    name: Vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Github vulnerability check
        uses: tierconnect-adm/github-vulnerability-steps@v0.0.3

